### ISSUE TITLE
Ghost

### ISSUE THREAD

**Issue by SinoX1337** [Ciallo-Ani/trikz#1]
Hello,

how i can Change the Ghost Names? the ghost.cfg is not working.
Can you pls help me.

Or can you Help me to get the bTimes-replay3 from blacky working with this version?

I can Pay if you want.

Discord SinoX1337#3109

**Comment by Nyano1337** [comment]
it's outdated, i dont support trikz anymore.
use his things and my things:
https://github.com/Smesh292/trikz
https://github.com/Ciallo-Ani/css-trikz-something-useful
